version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    networks:
      - shared-network

  api:
    container_name: pokemon_safari_api-test
    restart: unless-stopped
    image: pokemon-safari-backend-test
    build: .
    ports:
      - 3001:3001
    networks:
      - shared-network
    depends_on:
      - "db"
    environment:
      - NODE_ENV=test

networks:
  shared-network:
    driver: 'bridge'